steps:
  - name: node:install
    entrypoint: npm
    args: ["install"]
  - name: node:build
    entrypoint: npm
    args: ["run", "build"]
  - name: gcloud:build
    args: ["app", "deploy"]
timeout: "1600s"
